remote_theme: daattali/ beautiful-jekyllbeautiful-jekyll@main
plugins:
  - jekyll-remote-theme

tittle: Vechicle Recognizer
description: An image classification API the classifies 18 different types of vechicles

author:
  name: MD. Akib Iqbal Majumder
